<?php

namespace App\Services;

use App\Model\Category;
use App\Model\City;
use App\Model\Delivery;
use App\Model\Event;
use App\Model\PaymentMethod;
use App\Model\Transaction;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use App\Model\Certificate;
use App\Model\User;
use App\Notifications\ReportCertificatesAutoGeneratedClassroomTrainingEmail;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Notification;

class CreateCertificatesTrainingEventsService
{
    public static function generateCertificates($eventId = false)
    {

        $report = [];

        $query = Event::withDeliveries([Delivery::CLASSROM_TRAINING, Delivery::CORPORATE_TRAINING])->with('lessons');
        if($eventId){
            $query->where('id', $eventId);
        }
        $classroomTrainingEvents = $query->get();

        $not_ready = false;

        foreach ($classroomTrainingEvents as $event) {
            $finishClassDuration = $event->finishClassDuration();
            $diff = Carbon::now()->diff($finishClassDuration);
            if ($diff->d < 2 && $diff->y == 0 && $diff->m == 0) {
                $report_users = [];
                // It finished less than two days ago, we can create certificates.
                foreach ($event->users as $user) {
                    if (!$event->userHasCertificate($user)->first()) {
                        $view = 'admin.certificates.new_kc_certificate';
                        $template = 'new_kc_certificate';
                        $template_failed = 'new_kc_certificate';

                        $successMessage = (isset($event->event_info()['certificate']['has_certificate_exam']) && $event->event_info()['certificate']['has_certificate_exam'] && isset($event->event_info()['certificate']['messages']['success'])) ? $event->event_info()['certificate']['messages']['success'] : $event->title;
                        $failureMessage = isset($event->event_info()['certificate']['messages']['completion']) ? strip_tags($event->event_info()['certificate']['messages']['completion']) : '';
                        $certificateEventTitle = (isset($event->event_info()['certificate']['has_certificate_exam']) && $event->event_info()['certificate']['has_certificate_exam'] && isset($event->event_info()['certificate']['messages']['completion'])) ? $event->event_info()['certificate']['messages']['completion'] : $event->title;

                        if (!($cert = $event->userHasCertificate($user->id)->first())) {
                            $report_users[] = [
                                'kc_id' => $user->kc_id,
                                'name' => $user->name,
                            ];

                            $date = date('Y');
                            $cert = new Certificate;
                            $cert->success = true;
                            $cert->firstname = $user->firstname;
                            $cert->lastname = $user->lastname;
                            $cert->certificate_title = $certificateEventTitle;
                            $cert->credential = get_certifation_crendetial();
                            $createDate = strtotime(date('Y-m-d'));
                            $cert->create_date = $createDate;
                            $cert->expiration_date = strtotime(date('Y-m-d', strtotime('+24 months', strtotime(date('Y-m-d')))));
                            $cert->certification_date = date('F') . ' ' . date('Y');
                            $cert->template = $template;
                            $cert->save();

                            $cert->event()->save($event);
                            $cert->user()->save($user);
                        }
                    }
                }

                $report[] = [
                    'course' => $event->title,
                    'users' => $report_users,
                ];
            }else{
                $not_ready = true;
            }
        }

        if (count($report) > 0) {
            Notification::route('mail', 'info@knowcrunch.com')->notify(new ReportCertificatesAutoGeneratedClassroomTrainingEmail($report));
        }
        Notification::route('mail', 'lucasmuley@gmail.com')->notify(new ReportCertificatesAutoGeneratedClassroomTrainingEmail($report));

        $total = 0;
        foreach($report as $eve){
            $total += count($eve['users']);
        }
        if($eventId){
            return [
                'total' => $total,
                'report' => $report,
                'not_ready' => $not_ready
            ];
        }else{
            return count($report);
        }
    }
}
