---

DEPLOY_TIMESTAMP: "{{ $DEPLOY_TIMESTAMP }}"
CI_JOB_STAGE: "{{ $CI_JOB_STAGE }}"
CI_PROJECT_DIR: "{{ $CI_PROJECT_DIR }}/"
CI_COMMIT_REF_NAME: "{{ $CI_COMMIT_REF_NAME }}"
CI_PROJECT_NAME: "{{ $CI_PROJECT_NAME }}"
ROOT_PROJECT_NAME: "{{ $ROOT_PROJECT_NAME }}"
NODE_VERSION: "{{ $NODE_VERSION }}"
BUILDS_TO_KEEP: "3"
NVM_VERSION: "0.34.0"
COMPOSER_VERSION: "2.0.8"
SHARED_RESOURCES:
  - { name: storage, type: d }

APT_PACKAGES:
  - software-properties-common
  - zip
  - curl
  - openssl
  - vim
  - nginx

APT_PHP_PACKAGES:
  - php7.4-fpm
  - php7.4-common
  - php-imagick
  - php-pear
  - php7.4-bcmath
  - php7.4-cli
  - php7.4-curl
  - php7.4-mbstring
  - php7.4-mysql
  - php7.4-pgsql
  - php7.4-soap
  - php7.4-xml
  - php7.4-zip
  - php7.4-json
  - php7.4-dev
  - php7.4-mcrypt
  - php-mbstring
  - php7.4-apcu
  - php7.4-intl
  - libpcre3-dev
  - php7.4-gd
  - php7.4-imap
  - php7.4-opcache
  - php7.4-pdo
  - libmcrypt-dev
  - libjpeg-dev
  - libpng-dev
  - libfreetype6-dev
  - libbz2-dev
  - libpq-dev
  - libzip-dev
  - libffi-dev
