---

- name: Template logs_config to remote
  template:
    src: logs.config.j2
    dest: "/etc/promtail/config.d/{{ CI_PROJECT_NAME }}_{{ CI_JOB_STAGE }}_{{ CI_COMMIT_REF_NAME | lower }}_logs.config"
    mode: '0700'
  become: yes
  ignore_errors: True

- name: Merge promtail config.d
  ansible.builtin.assemble:
    src: /etc/promtail/config.d/
    dest: /etc/promtail/config.yml
  become: yes
  ignore_errors: True

- name: Restart promtail
  systemd:
    daemon_reload: true
    name: promtail
    state: restarted
  when: not ansible_check_mode
  become: yes
  ignore_errors: True