name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.STAGING_DEPLOYMENT_SSH_KEY }}

    - name: Run deploy script on server
      run: |
        ssh -o StrictHostKeyChecking=no 99008-6348@gate.j.scaleforce.net -p 3022 'bash /var/www/webroot/deploy.sh website'
