name: Format (JS)

on:
  pull_request:
    # Trigger the workflow on pull request activity when at least one js file in changes
    paths-ignore:
      - '**.php'

jobs:
  prettify-fixer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node 20
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install
        run: npm i

      - name: Run prettify
        run: npm run prettify:fix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply prettify formatting changes
          branch: ${{ github.head_ref }}
